---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - watchers.malek.dev
  resources:
  - watchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watchers.malek.dev
  resources:
  - watchers/finalizers
  verbs:
  - update
- apiGroups:
  - watchers.malek.dev
  resources:
  - watchers/status
  verbs:
  - get
  - patch
  - update
